CREATE USER notes_user WITH PASSWORD 'your_password';

CREATE DATABASE notes_db OWNER notes_user;

GRANT ALL PRIVILEGES ON DATABASE notes_db TO notes_user;

\c notes_db

GRANT USAGE, CREATE ON SCHEMA public TO notes_user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO notes_user;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO notes_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO notes_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO notes_user;
